Revert "Redirect base exec path for Python CLI scripts if `rocm[devel]` is installed" (#2472)
Reverts ROCm/TheRock#2428

See https://github.com/ROCm/TheRock/pull/2428#discussion_r2599650550.
The new test fails on Linux:
```bash 
python3.12 -m venv 3.12.venv && source 3.12.venv/bin/activate
python -m pip install --index-url=https://rocm.nightlies.amd.com/v2-staging/gfx110X-all rocm[libraries,devel]
# Successfully installed rocm-7.11.0a20251208 rocm-sdk-core-7.11.0a20251208 rocm-sdk-devel-7.11.0a20251208 rocm-sdk-libraries-gfx110X-all-7.11.0a20251208

rocm-sdk test

...

======================================================================
FAIL: testCLIUsesDevelRootPath (rocm_sdk.tests.devel_test.ROCmDevelTest.testCLIUsesDevelRootPath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nod/dev/scratch/therock/3.12.venv/lib/python3.12/site-packages/rocm_sdk/tests/devel_test.py", line 97, in testCLIUsesDevelRootPath
    self.assertEqual(
AssertionError: Posix[29 chars]herock/3.12.venv/lib/python3.12/site-packages/_rocm_sdk_devel') != Posix[29 chars]herock/3.12.venv/lib/python3.12/site-packages/_rocm_sdk_core') : Expected `hipconfig --rocmpath` to return /home/nod/dev/scratch/therock/3.12.venv/lib/python3.12/site-packages/_rocm_sdk_devel, not /home/nod/dev/scratch/therock/3.12.venv/lib/python3.12/site-packages/_rocm_sdk_core

----------------------------------------------------------------------
Ran 26 tests in 3.900s

FAILED (failures=1, skipped=2)
```


This is because the `rocm[devel]` Python package uses symlinks on Linux
while it uses hardlinks on Windows and the symlinks still report their
install path as `_rocm_sdk_core`.

I'm considering a few ways to fix this
(https://github.com/ROCm/TheRock/issues/1880#issuecomment-3628650180),
but I'll just revert for now.